In [22]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets

![](https://huayu.huabaike.com/olduploads/oldimg/body/20170915171149_984509.jpg)

In [13]:
# 鸢尾花因为自然环境不同，所以类别可以细分
iris = datasets.load_iris()
iris
# data二维数组：一维数组是一朵花，四个特征属性，150个一维数组，代表150个样本
# target一维数组：三个花的分类
# target_names：三个花类别的名字

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
X = iris['data']
y = iris['target']
# (150, 4) 150代表150个样本，4代表4个属性：花萼长、宽；花瓣长、宽
X.shape

(150, 4)

In [16]:
# 将数据划分，一分为二：一部分用于训练，另一部分用于测试
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
# 将顺序打乱
index = np.arange(150)
index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [19]:
# 打乱顺序
np.random.shuffle(index)
index

array([ 25, 129, 145,   8, 133, 147,   1,  18,  67,  34, 120,  28,  43,
       112,  68,  77, 131, 138,  33, 143,  60,  32,  88,  24, 146, 149,
       144, 106,  99,   5,  39,  90, 127, 119, 142,  58,  96,  59,  38,
        47,  55,   9,  98, 116,  17,  56, 115,  20, 114,  16,  45, 122,
        93,  27, 111, 137,  48,  54,  92,  69,  80,  73,  89,  21,  49,
        13,  76, 141,  95, 134,  23,  31,  85,  65,  94,  64,   4, 104,
       139,  61,  84, 121,  37,  91,  15,  30, 124, 108,  40,  14,  53,
        87, 148, 103,  78, 118,  79, 128,  57,  66,  83,  42, 126,  35,
       117, 125,  71,  82, 101,  12, 113,  52, 132, 105,  62,  50,  97,
       130, 102,   6,  41,  75, 107,   0,  36,  70,   2,  63,  11,  44,
       109,  51,  29, 136,  46, 100,  19,  72,   7,  26,  10,  74,   3,
       140,  22,  81, 110, 123, 135,  86])

In [31]:
# 前100个取出来算法学习，留下的50个使用算法预测（验证算法是否可靠）
X_train,X_test = X[index[:100]],X[index[100:]]
y_train,y_test = y[index[:100]],y[index[-50:]] #-50跟100一样

In [35]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_ = knn.predict(X_test)

In [36]:
type(X_train)

numpy.ndarray

In [33]:
print(y_)
print('--------')
print(y_test)

[2 0 2 0 2 2 1 1 2 0 2 1 2 2 1 1 1 2 2 0 0 1 2 0 0 2 0 1 0 0 2 1 0 2 0 2 0
 2 0 0 0 1 0 2 0 1 2 2 2 1]
--------
[1 0 2 0 2 2 1 1 2 0 2 1 2 2 1 1 1 2 2 0 0 1 2 0 0 1 0 1 0 0 2 1 0 2 0 2 0
 1 0 0 0 1 0 2 0 1 2 2 2 1]


In [37]:
y_ == y_test

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [38]:
# 准确率
(y_ == y_test).sum()/50

0.94

In [39]:
knn.score(X_test,y_test)

0.94

In [40]:
# 算法返回的结果一般使用变量加一个杠
proba_ = knn.predict_proba(X_test)
# proba_代表概率，[0. , 0. , 1. ]就代表是类别2
proba_

array([[0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.4, 0.6],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0.4, 0.6],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. 